<a href="https://colab.research.google.com/github/SrujanBoppa/GitHub-Basics/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [3]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

result = arr1 + arr2
print(result)

print(type(arr1 * 2))
print(arr1 * 2)


[11 22 33 44 55]
<class 'numpy.ndarray'>
[ 2  4  6  8 10]


In [5]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
full_array=np.full((2,3),7)
print(full_array)

[[7 7 7]
 [7 7 7]]


In [9]:
# Using Python lists
list1 = [1, 2, 3, 4, 5]
list2 = [10, 20, 30, 40, 50]

result = []

for i in range(len(list1)):
    result.append(list1[i] + list2[i])

print(list1 + list2)   # Concatenation
print(result)          # Element-wise addition
# Output: [11, 22, 33, 44, 55]


# Using NumPy arrays
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

result = arr1 + arr2
print(result)          # [11 22 33 44 55]

print(type(arr1 * 2))  # <class 'numpy.ndarray'>
print(arr1 * 2)        # [ 2  4  6  8 10]


[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11, 22, 33, 44, 55]
[11 22 33 44 55]
<class 'numpy.ndarray'>
[ 2  4  6  8 10]


In [10]:
import numpy as np

# Define the matrices based on the provided output
mat1 = np.array([[1, 2],
                 [3, 4]])

mat2 = np.array([[5, 6],
                 [7, 8]])

# Element-wise multiplication
print(mat1 * mat2)
# Output:
# [[ 5 12]
#  [21 32]]

# Matrix multiplication (dot product)
print(np.dot(mat1, mat2))
# Output:
# [[19 22]
#  [43 50]]


[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))       # 15
print(arr.sum())        # 15 (method syntax)
print(np.mean(arr))      # 3.0
print(np.std(arr))       # 1.4142135623730951 (standard deviation)
print(np.var(arr))       # 2.0 (variance)
print(np.min(arr))       # 1
print(np.max(arr))       # 5
print(np.argmin(arr))    # 0 (index of minimum)
print(np.argmax(arr))    # 4 (index of maximum)


15
15
3.0
1.4142135623730951
2.0
1
5
0
4


In [12]:
import numpy as np

# Define two 2x2 matrices
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Perform element-wise addition
result = mat1 + mat2

print(result)
# Output:
# [[ 6  8]
#  [10 12]]


[[ 6  8]
 [10 12]]


In [13]:
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print(arr_2d.sum())            # Output: 21

# Sum along rows (column sums)
print(arr_2d.sum(axis=0))      # Output: [5 7 9]

# Sum along columns (row sums)
print(arr_2d.sum(axis=1))      # Output: [ 6 15]

# Mean along rows (column means)
print(arr_2d.mean(axis=0))     # Output: [2.5 3.5 4.5]

# Maximum along columns (row max)
print(arr_2d.max(axis=1))      # Output: [3 6]


21
[5 7 9]
[ 6 15]
[2.5 3.5 4.5]
[3 6]


EDGE CASES

In [14]:
import numpy as np

# Example 1: Dividing by zero
arr1 = np.array([1, 2, 3])
result1 = arr1 / 0
print(result1)
# Output: [inf inf inf]
# Note: This triggers a RuntimeWarning: divide by zero encountered in divide

# Example 2: Element-wise division with zeros
arr2 = np.array([0, 1, 2])
result2 = arr2 / arr2
print(result2)
# Output: [nan 1. 1.]
# Note: 0/0 results in 'nan' (not a number). This triggers a RuntimeWarning: invalid value encountered in divide


[inf inf inf]
[nan  1.  1.]


/tmp/ipython-input-4071541026.py:5: RuntimeWarning: divide by zero encountered in divide
  result1 = arr1 / 0
/tmp/ipython-input-4071541026.py:12: RuntimeWarning: invalid value encountered in divide
  result2 = arr2 / arr2


RESHAPE THE ARRAY

In [15]:
import numpy as np

# 1. Creating a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3D Array Shape: {arr_3d.shape}")
print(arr_3d)

# 2. Creating a 1D array using arange
arr = np.arange(12)
print("\n1D Array:")
print(arr)

# 3. Reshaping to 3x4 (3 rows, 4 columns)
arr_2d_3x4 = arr.reshape(3, 4)
print("\nReshaped to 3x4:")
print(arr_2d_3x4)

# 4. Reshaping to 4x3 (4 rows, 3 columns)
arr_2d_4x3 = arr.reshape(4, 3)
print("\nReshaped to 4x3:")
print(arr_2d_4x3)


3D Array Shape: (2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

1D Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 4x3:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
